### ISSUE TITLE
VIN Allow List

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#104]
This would only be applicable to a subset of TWCs, since not all of them support reporting the VIN.  There was a Reddit post where someone was concerned about having the TWC outside, since anyone could pull up during the day and charge.  So here's a random idea:

Now that we support getting the VIN from the TWC, it would be fairly straightforward to check that the VIN matches one of the VINs on the Tesla account and/or an explicit list in the config file, and stop responding to that TWC (or send a stop-charging command) if an unauthorized car starts charging.

The harder pieces would be:
- Recovery; if we do that, we won't know when the offending vehicle is gone.  Maybe just clear it at the next policy change, which means that the Charge Now button on the web interface unlocks it?
- Support and messaging; if the feature is configured and the TWC doesn't support giving us the VIN, we would need to prominently display an error.

**Comment by ngardiner** [comment]
This would be a great feature

**Comment by mattiasclaesson** [comment]
[(https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white)]

**Comment by MikeBishop** [comment]
Fair enough.  Now, if we could just get Master and Slave out of the codebase....

**Comment by mattiasclaesson** [comment]
> Fair enough. Now, if we could just get Master and Slave out of the codebase....

yeah, we do what we can!

**Comment by ngardiner** [comment]
This has been implemented in #265
