### ISSUE TITLE
Real Power adjustment 

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#163]
There was some code recently that doesn't appear to be on a PR I can find that adjusted power factors for charging. There was a question whether it was generally true or simply an artifact of that particular install.

FWIW, I now have a CT clamp monitoring my charging circuit with Sense, and this is what I see:

| Current | Wattage TWC reports | Wattage Sense measures |
|---|---|---|
| 6A | 1,487 W | 1,285 W |
| 48A | 11,717W | 10,485 W |

**Comment by dschuesae** [comment]
Have a look here: https://github.com/ngardiner/TWCManager/pull/159
