### ISSUE TITLE
TWCManager does not wake up the car anymore

### ISSUE THREAD

**Issue by dschuesae** [ngardiner/TWCManager#166]
As soon as the car sleeps, TWCManager can not wake it up anymore. From this moment on the car won't be available anymore via api (also Tesla App cannot access it anymore) until you completely restart your Raspberry (restart of TWCManager Python Script does not help). If you wake up the car via Tesla App before start charging - no problem, everything works as expected.

**Comment by dschuesae** [comment]
I added a sleep for 5 seconds after wake up call. And it seems to work again. Will make some tests tomorrow.

**Comment by MikeBishop** [comment]
Resolved in #171, but not linked.

**Comment by dschuesae** [comment]
I had this again 2 time out of 10 days...
