### ISSUE TITLE
Do we need the empty schedule table on the right?

### ISSUE THREAD

**Issue by hopfi2k** [ngardiner/TWCManager#181]
I'm continuing working on the GUI and wonder if we need this empty "schedule" table on the right side of the home screen for any reason? In case it get's any future use shouldn't it be moved to the 'schedule' page?

**Comment by ngardiner** [comment]
The schedule page is for configuring the schedule. The schedule table is
for displaying the schedule.

Both are under current development in a branch under the main repo if you
are interested in what it will (shortly) look like

**Comment by hopfi2k** [comment]
Thanks very much. I'll have a look at this branch.

**Comment by ngardiner** [comment]
Let's continue this conversation in the GUI updates issue
