### ISSUE TITLE
JS function for managing Charge Now runs on all pages

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#195]
While it doesn't break functionality that this code errors out on other pages, it does make using a browser debug console a pain, because it's constantly seizing on the uncaught exception.

**Comment by ngardiner** [comment]
Good point - I've updated the templates to include the javascript functions only for the status screen - just want to check that you're seeing the messages gone now as well?

**Comment by MikeBishop** [comment]
Yes, this appears to be fixed now.
