### ISSUE TITLE
Support for more time variables

### ISSUE THREAD

**Issue by GMerg** [ngardiner/TWCManager#199]
Right now it seems I can only use **tm_hour** when customizing the policy rules.
I would need to have access to **tm_wday** to define a new charging rule to apply before weekends.
Would it be possible to support the rest?

- tm_year | (for example, 1993)
- tm_mon | range [1, 12]
- tm_mday | range [1, 31]
- tm_min | range [0, 59]
- tm_sec | range [0, 61]
- tm_wday | range [0, 6], Monday is 0
- tm_yday | range [1, 366]

**Comment by MikeBishop** [comment]
Try the branch `tm_star`, where I've pushed a change that should support all the time properties.

**Comment by GMerg** [comment]
Thats great! Thanks for the changes...just what I need! :)
