### ISSUE TITLE
Error in "/lib/TWCManager/Control/HTTPControl.py" line 450 + possible fix

### ISSUE THREAD

**Issue by GMerg** [ngardiner/TWCManager#217]
When having a policy with nested conditions, you get an error when showing policy in web interface.
The file has to be changed from:

**`page += "<td>" + condition + "</td>"`**

to:

**`page += "<td>" + str(condition) + "</td>"`**

A sample policy in **/etc/twcmanager/config.json** to debug this:
```
...
"extend":{
...
"after":[
          { "name": "Charge on FR for SA",
            "match": [ "modules.TeslaAPI.minBatteryLevelAtHome", "tm_hour", "tm_wday", [ "tm_mon", "tm_mon" ] ],
            "condition": [ "lt", "gte", "eq", ["gte", "lte"] ],
            "value": [ 80, 15, 4, [ 10, 2] ],
            "charge_amps": 12
          },
....
```

**Comment by MikeBishop** [comment]
Ooh, good catch.  I recently rewrote my policies so I don't have anything nested right now, so I didn't encounter this in my testing.  Yes, that change keeps it from crashing, but doesn't actually give you the same view into why the policies are / aren't matching.

**Comment by GMerg** [comment]
OK, glad I could help in some way. :)

**Comment by ngardiner** [comment]
Thanks for this @GMerg - I'm doing some work on the UI now as part of an upcoming feature, so I'm going to merge this in with that code now and it will be in v1.2.2 shortly. Thanks again :)
