### ISSUE TITLE
Change of Authentication at Tesla API

### ISSUE THREAD

**Issue by Der-Kieler** [ngardiner/TWCManager#218]
https://tesla-api.timdorr.com/api-basics/authentication

As I understand is an exisitng Token working till is suspended. But then the new Token can only be generated if the new way to get it is used.
Will you fix this for the TWCManager or is this no problem?

**Comment by ngardiner** [comment]
We're tracking this in #157, it is fixed for non-MFA users but there will need to be an additional change to support MFA authentication, which is likely coming at the end of this week, workload depending
