### ISSUE TITLE
strstart = 10 in policyValue() ??

### ISSUE THREAD

**Issue by AndySchroder** [ngardiner/TWCManager#23]
In the function `policyValue` in `TWCMaster.py` there is the variable `strstart = 10`. However, `len("settings.") = 9`. Since python indexes from 0, why do you set `strstart = 10` ? I think this is a bug.

**Comment by ngardiner** [comment]
Nice pickup, thanks @AndySchroder!

**Comment by ngardiner** [comment]
Fixed b14085e
