### ISSUE TITLE
Modern Web: Charge Now in Portrait

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#245]
![Screenshot_20210307-110515](https://user-images.githubusercontent.com/4273797/110246322-283cce80-7f35-11eb-99c6-e9c6005585fa.jpg)
I'd suggest a minimum width on these controls, so that if the screen is narrow, each selector fills the width and the controls arrange vertically. The current layout makes it difficult to select a value accurately. (I initially thought these were toggle switches, not sliders!)

**Comment by hopfi2k** [comment]
I've spent a fair amount of work, making the modern web design more responsive and will commit these changes shortly.

**Comment by VIDGuide** [comment]
I've got a fix for this one in my current pull request #317 

Responsive mode will stack like this:
![](https://user-images.githubusercontent.com/3220618/123505937-f480e280-d6a4-11eb-8a7e-d602ba8862ae.png)

**Comment by MikeBishop** [comment]
Closing since #317 is merged.
