### ISSUE TITLE
Charge Now - Policy lag when switching policy

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#261]
Just to track this: Would be good to identify if there's a reasonable way to accelerate the change of policy when Charge Now is first activated or is cancelled - the latency is quite noticeable and given it's usually a UI triggered command, the delay feels significant.

**Comment by MikeBishop** [comment]
Seems simple enough -- if the Charge Now command reached into the Policy module and reset `self.lastPolicyCheck` to zero, the next policy change should happen in around a second.  If you want to keep more modularity, the Policy module could expose an API that does that.

For that matter, after resetting, it could call `setChargingPerPolicy()` immediately thereafter.
