### ISSUE TITLE
Powerwall API changes

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#28]
According to https://www.reddit.com/r/teslamotors/comments/f5dbf7/psa_power_api_changes/, the cloud API endpoint has changed for Powerwall. This might not impact the local endpoint, or the change might be coming in a future firmware update, but it needs to be validated.

**Comment by ngardiner** [comment]
Thanks for the heads up, @MikeBishop. We'll need to keep an eye on this.

**Comment by MikeBishop** [comment]
It appears the local endpoint has not changed so far.  However, the new vehicle-integration features suggest that the Powerwall exposes a finer-grained API for fetching allowable charging speeds that might be of interest in the future.
