### ISSUE TITLE
Release Milestones - v1.2.2

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#288]
It would be nice to get v1.2.2 released as it has full MFA support included. Before we do, there's a few things that might need to get done:

- **done** Need to resolve what looks like an issue we introduced for Tesla Login when the API backoff code was merged. It seems that we no longer meet the criteria in the ```process_teslalogin``` > ```car_api_available``` function under some cases where current tokens are invalid (and probably when they're valid, too). 
   - It might just make sense to restructure ```process_teslalogin``` > ```car_api_available``` to always attempt login regardless of API state, but I'm unsure if the changes have also stopped us from predictably detecting revoked credentials, this needs testing/bug hunting because it has the potential to affect people in future if they change password. 
   - From the look of it, it's really not nicely structured and is quite legacy so there's some room for refactoring, but also wide impact
   - It's equally possible that nothing has changed fundamentally, but the report in the Tesla MFA issue #276 is very compelling, the behaviour seems to have changed and was not modified by MFA implementation.
- **done** Would be nice if I could get the new offset code in by then as well, so people can set offsets in watts without having to worry about voltage fluctuations causing additional variance for consumption values. I'll try to get the lengthy list of outstanding steps done this weekend and get it merged.
- **done** @MikeBishop - any priorities that you'd like included before we cut a stable version and move on to a new dev version?
- Tesla Auth changes? Seem to have been rolled back for now - might release regardless and follow up with a subsequent release if it's changed again.

**Comment by MikeBishop** [comment]
I went ahead and merged #279; nothing else outstanding of mine seems particularly critical.

**Comment by ngardiner** [comment]
I'm going to add #295 to the list for me to fix as well, despite not having made much headroom with the above (but I have high hopes for this week), I am just holding steady at the moment on that first auth flow change because Tesla are playing with things right now on the Auth side and I don't think it would make sense to release 1.2.2 right before they add Captcha back in, but I regretfully didn't capture the flow with Captcha in it so I can't plan for it's support before they put it back.

**Comment by ngardiner** [comment]
Fixed the remaining auth issue so we've hit all the milestones for v1.2.2 release. I think it's time to roll it up.

Just before I do, I want to tweak the CI mechanisms to create a release on tagging of the version including a pypi and docker package version. I'll work out exactly what we need in GitHub Actions to do that cleanly and then I'll cut a release.

**Comment by ngardiner** [comment]
Added the CI pipeline logic to automatically create docker and (starting from next version) PyPi releases on release creation, so everything is in place now, closing this off.
