### ISSUE TITLE
Can't read sensor.xxxx from Home Assistant

### ISSUE THREAD

**Issue by KirkKirk** [ngardiner/TWCManager#290]
Hi Guys,

I am pleased to see a successful growing project as TWCManager is.
As I have limited knowledge in coding, I reach the point where I need guidance for a probably basic issue.
I did all electronics and installation so I can connect to my TWC and access the TWCM GUI.
The problem is that I can't access my HA to get a reading of sensors for my solar production and power consumption.
For login in my HA, I am using https://192.168.1.222:8123 with 2fa. I was following the instructions in the TWCM dosc, and probably I am making some basic mistake for which I need help to find it.
Can you please guide me to find a step-by-step example for the biginer for how to do it? 

Thanks in advance,
Kirk

**Comment by KirkKirk** [comment]
As I said, I am not good with coding in python, so can someone tell me what this means?


May 28 18:42:00 Rass1 python3[1066]: 18:42:00 TWCManager 20 Charge when above 12A (minAmpsPerTWC).
May 28 18:42:00 Rass1 python3[1066]: 18:42:00 TWCManager 20 BackgroundError: Traceback (most recent call last):
May 28 18:42:00 Rass1 python3[1066]:   File "/home/pi/TWCManager/TWCManager.py", line 275, in background_tasks_thread
May 28 18:42:00 Rass1 python3[1066]:     master.saveSettings()
May 28 18:42:00 Rass1 python3[1066]:   File "/home/pi/TWCManager/lib/TWCManager/TWCMaster.py", line 946, in saveSettings
May 28 18:42:00 Rass1 python3[1066]:     with open(fileName, "w") as outconfig:
May 28 18:42:00 Rass1 python3[1066]: PermissionError: [Errno 13] Permission denied: '/etc/twcmanager/settings.json'
May 28 18:42:00 Rass1 python3[1066]: , occurred when processing background task
May 28 18:42:30 Rass1 python3[1066]: 18:42:30 TWCManager 20 Green energy generates 0W, Consumption 0W, Charger Load 0W
May 28 18:42:30 Rass1 python3[1066]: 18:42:30 TWCManager 20 Limiting charging to 0.00A - 0.00A = 0.00A.
May 28 18:42:30 Rass1 python3[1066]: 18:42:30 TWCManager 20 Charge when above 12A (minAmpsPerTWC).
May 28 18:42:59 Rass1 python3[1066]: 18:42:59 TWCManager 20 Slave TWC 4935: Delivered 2250 kWh, voltage per phase: (250, 0, 0).
May 28 18:43:01 Rass1 python3[1066]: 18:43:01 TWCManager 20 Green energy generates 0W, Consumption 0W, Charger Load 0W

**Comment by ngardiner** [comment]
The error above indicates a permissions error, could you please run the following command:

```
chown -R pi:pi /etc/twcmanager
```

In terms of HomeAssistant, is the issue that you are seeing that you do not see the sensors in the entities list? Did you create a long-lived API key per the documentation and put it in your ```config.yaml``` under the Status section of the config?

```
"apiKey": "abcdefg"
```

Or is the issue that you are unable to read your generation / consumption values from HASS, which is configured under the sources section of config.yaml?

**Comment by KirkKirk** [comment]
Hi @ngardiner, 
Thank you for your help and guidance. 
Before I came back to you, I spend many hours reading and trying to get some results but no luck.
Truly, I feel like a total dummy, but I will not give up.
The first command fixed the permission error after I add sudo at the beginning. (it was an easy one,  thanks)
For API, I think I tried all variations that I found in the documentation and blogs and still, I don't understand where I make mistakes.
I did create an API key multiple times and added it in "apiKey", and I was changing the useHttps to true or false but no changes.
I couldn't get any data from HASS to TWCM.
Start from scratch is the only thing that I haven't try.
Before I rebuild from scratch my Raspberry Pi 3 and reinstall TWCManager, can you please show me an example of already configured TWCM config.json and HASS configuration.yaml where api: is defined?

Thanks,
Kirk

**Comment by KirkKirk** [comment]
Sorry for bought you but I can't make it work.
Last, I attempted to install it in docker as well, where I couldn't start it. Again issues with the permission or so.
I am not familiar with Raspberry Pi, so I will try to reinstall it tomorrow.
I believe the issue is in my limited knowledge, as all instructions are for Raspberry Pi Zero W, and I believe it is not the same for Raspberry Pi 3 that I bought just for this project. 

I would appreciate it if you could tell me if I should continue with the existing Pi 3 (but I will need instructions) or purchase Pi Zero.

Thanks,

**Comment by colwilliamsnz** [comment]
Shouldn't matter what PI you use here. One things I notice is you reference https://192.168.1.222:8123

Are you actually using HTTPS? Out of the box, Home Assistant uses just HTTP. Test if you can access the above URL from a browser to get to HASS and if you can't, there lies your problem :)

**Comment by KirkKirk** [comment]
Thank you for your help. I've tried all combinations, including your example. I tried to use my my.duckdns.org:8123, but it didn't work. In my case, for access, I am using https//192.168.1.222:8123 or from outside https://--.duckdns.org:8123 and never have issues with the accession it. When the first-time login in from any device, to HA I have to log in with a username, password, and 2fa, but I don't need to do it after it, so I believe HA API is working fine. 
I think I am doing something wrong in installing Pi OS itself, so I'll try it again. 
As I am using https, do I need any API related settings in HA?

**Comment by colwilliamsnz** [comment]
I don't use SSL for HASS as its a level of complexity I don't need (I use Nabu Casa for remote access, because it just works and costs me a cup of coffee each month :).

I suggest you enable enhanced logging in TWCM as this should show any errors relating to HASS authentication. I guess its always possible that 2FA is getting in the way so check in the HASS logs too (authentication issues will be logged in here from TWCM if there are any).

**Comment by KirkKirk** [comment]
Definitely, the issue is not related to HomeAssistant.
This project I like very much and on the way to use it, I learn some things for which I am double grateful to the author of TWCM and all contributors.

Where I am now:  
I installed fresh HASS with no SSH, on Pi3 installed Raspberry OS, updated it to Buster, Installed Docker, Installed TWCManager v1.2.2, adapted config.json.
Still no import of any HASS sensor.xxx
On HTTP:192.168.1.xxx:8123 I can access HASS via Pi browser where TWCManager is installed.

TWCM shows the following.:
pi@rass1:~/TWCManager $
pi@rass1:~/TWCManager $ docker-compose -f contrib/docker/docker-compose.yml up
Starting docker_twcmanager_1 ... done
Attaching to docker_twcmanager_1
twcmanager_1  | 09:49:22 HTTPContro 20 Serving at port: 8080
twcmanager_1  | 09:49:22 TWCManager 20 TWC Manager starting as fake Master with id 7777 and sign 77
twcmanager_1  | 09:49:24 TWCManager 20 32.00 amp slave TWC 4935 is ready to link.  Sign: 7B
twcmanager_1  | 09:49:24 TWCManager 20 Set slave TWC 4935 protocolVersion to 2, minAmpsTWCSupports to 6.
twcmanager_1  | 09:49:25 Policy     20 New policy selected; changing to Track Green Energy
twcmanager_1  | 09:49:25 TWCSlave   20 SHB 4935: 00 00.00/00.00A 0000 0000  M: 09 00.00/00.00A 0000 0000
twcmanager_1  | 09:49:25 TWCSlave   20 Slave power for TWCID 4935, status: 0
twcmanager_1  | 09:49:25 TWCManager 20 Limiting charging to 0.00A - 0.00A = 0.00A.
twcmanager_1  | 09:49:25 TWCManager 20 Charge when above 12A (minAmpsPerTWC).
twcmanager_1  | 09:49:25 TWCManager 20 Slave TWC 4935: Delivered 2326 kWh, voltage per phase: (254, 0, 0).

I noticed that the HASS.py haven't changed at all. Is it normal?


import logging

logger = logging.getLogger(__name__.rsplit(".")[-1])


class HASS:

    # HomeAssistant EMS Module
    # Fetches Consumption and Generation details from HomeAssistant

    import requests
    import time

    apiKey = None
    cacheTime = 10
    config = None
    configConfig = None
    configHASS = None
    consumedW = 0
    fetchFailed = False
    generatedW = 0
    hassEntityConsumption = None
    hassEntityGeneration = None
    lastFetch = 0
    master = None
    status = False
    serverIP = None
    serverPort = 8123
    useHttps = False
    timeout = 2

    def __init__(self, master):
        self.master = master
        self.config = master.config
        try:


I will appreciate it if someone is willing to help me identify the issue.
I can give access via TeamViewer or someone will help with really very very detailed step by step of how to install TWCM (I tried all installation versions)

**Comment by ngardiner** [comment]
Hi @KirkKirk,

The best way for us to help will be if you can do this please:

Edit your ```/etc/twcmanager/config.json``` file and post the following parts of the config, with IP/API key xxxxxx out:

```
    "sources":{
        "HASS": {
            "enabled": false,
            "serverIP": "192.168.xx.xx",
            "serverPort": "8123",
            "apiKey": "xxxxx",
            "hassEntityConsumption": "sensor.consumption_power_live",
            "hassEntityGeneration":  "sensor.inverter_power_live"
        },

    "status": {
        "HASS": {
            "enabled": true,
            "serverIP": "192.168.xx.xx",
            "serverPort": "8123",
            "apiKey": "xxxxx"
        },
```

Finally, if you could please run this command from the command line of your RPi machine running TWCManager:

```
openssl s_client -connect your.hass.ip:8123
```

That should be plenty of info for us to work out what's enabled/disabled/configured and why it isn't working for you.

**Comment by ngardiner** [comment]
Also, just to confirm, you should not need to use your duckdns name in any homeassistant config as long as it's on your internal network and we are as well. Just the IP address and port of the homeassistant server should be all you need.

**Comment by KirkKirk** [comment]
Hi @ngardiner and all

Before everything else, THANK YOU for your great work and help the world be a better place.

Just a minute before I saw your response I figured out how dumb I am.

In the past 10 days, the config.json, I was editing via file browser (text editor) which in reality is /home/pi/TWCManager/etc/twcmanager/config.json

After I reinstall Pi (maybe it was the 20th time) and Install TWCManager in manual, for the first time config.jason I edited from CLI with nano /etc/twcmanager/config.json and guess what..... everything worked as it should.

Now I will make a fresh install in a docker and tomorrow I will use it for charging.

In meantime tonight, with great pleasure, I'll find your coffee button.

Please forgive me for wasting your and everyone else's time.

Thanks,
Kirk

**Comment by ngardiner** [comment]
Great to hear it's working @KirkKirk - doing a bit of a cleanup so I'll close off the issue now
