### ISSUE TITLE
Permissions for config.json?

### ISSUE THREAD

**Issue by colwilliamsnz** [ngardiner/TWCManager#291]
Hi, Linux newbie here :) I get the following error from the web interface when saving settings. Can someone shed some light on how I fix this please? TWCManager is configured to run as a service.

"We experienced an error trying to save your settings. This means that while your current settings will be retained for the current session, they will not be saved if TWCManager exits. Please check the permissions on /etc/twcmanager/settings.json and try saving your settings again"

I thought it would be as simple as changing permissions as follows (but apparently not).

chmod +arw ...

**Comment by colwilliamsnz** [comment]
Found the fix...and for reference :)

chown -R pi:pi /etc/twcmanager

**Comment by mikey4321** [comment]
Thanks @colwilliamsnz.

For other people's benefit I had to run the chown as `sudo chown -R pi:pi /etc/twcmanager` with sudo to fix it.
