### ISSUE TITLE
Modern Theme: Variable "defaultChargeAmps"  is not initialized.

### ISSUE THREAD

**Issue by Saftwerk** [ngardiner/TWCManager#295]
After reloading the Modern Theme page there is no value at the right slider:
![image](https://user-images.githubusercontent.com/19615255/120078189-77b31680-c0ae-11eb-9da5-95217e2e911a.png)

File: lib\TWCManager\Control\themes\Modern\main.html.j2
Error in line 293: Variable **defaultChargeAmps** is not initialized.

**Comment by ngardiner** [comment]
This is a priority to fix

**Comment by ngardiner** [comment]
Fixed in 4cc5bdb
