### ISSUE TITLE
v1 TWC display issues in v1.2.2 - fields missing/blank

### ISSUE THREAD

**Issue by Squazel** [ngardiner/TWCManager#310]
Working correctly in v1.2.1, but now older "v1" HPWCs/TWCs (that came with AU cars in 2015/2016?) are not displaying key data:

![image](https://user-images.githubusercontent.com/69331286/122601554-cf90dc00-d0b4-11eb-9880-ce7f06338faf.png)

The second row is a v1 charger - differences from v1.2.1 are:
* Truncated leading zero at start of ID
* Missing/blank State, Version, Max Amps, Amps Offered, Amps In Use, Last Heartbeat (previously poplated correctly in v1.2.1)

Similarly in the modern theme:
![image](https://user-images.githubusercontent.com/69331286/122601755-20a0d000-d0b5-11eb-9f6e-890204d2d6e6.png)
* ID is okay, but other key data (version / state / amps offered / in use) are blank

Note that the unit appears to respond to charging commands and works as expected, so this appears to just be a display issue.

**Comment by ngardiner** [comment]
Sorry about that, @Squazel. Going to take a look as a high priority and get that fixed.

**Comment by Squazel** [comment]
Hi @ngardiner - although this fix appears to have resolved the missing leading zero in the legacy/default web interface, it does not appear to have addressed any of the other missing data fields. Could you please review/reopen this one?

**Comment by ngardiner** [comment]
Thanks for letting me know, @Squazel 

Could I please get you to capture something for me. It might be called something different in your browser, but if you could please go to the TWCManager web interface in Firefox or Chrome and open the Developer Toolbar:

![image](https://user-images.githubusercontent.com/25845228/130559806-53c06af5-9695-4d23-83c4-12df02b80602.png)

If you could refresh, and let it run for a while, and then save the HAR file (it's under the cog button in Firefox or menu in Chrome) and email it to me that would help a lot!

**Comment by ngardiner** [comment]
Will be fixed in v1.2.4 - thanks again @Squazel for your help troubleshooting this one
