### ISSUE TITLE
saveSettings API generates a HTTP 404 error (and fails to save settings)

### ISSUE THREAD

**Issue by colwilliamsnz** [ngardiner/TWCManager#334]
Version 1.2.2. When calling saveSettings API I'm getting a 404 error and the settings I've updated using setScheduledCharging are not saved.

curl -i -X POST -d "" http://192.168.1.73:8080/api/saveSettings

HTTP/1.0 404 Not Found
Server: BaseHTTP/0.6 Python/3.7.3

**Comment by ngardiner** [comment]
saveSettings is new in v1.2.3. We'll be doing a release very shortly, if that helps.

**Comment by colwilliamsnz** [comment]
Good stuff Nathan. Looking forward to 1.2.3!
