### ISSUE TITLE
Incorrect email or password.

### ISSUE THREAD

**Issue by soso1999** [ngardiner/TWCManager#346]
Hi there!
i am getting en error "Incorrect email or password"  when i am trying to connect to my Tesla-Account. What am i doing wrong? Accountname and Password are correct.
Thanks!

**Comment by KirkKirk** [comment]
@soso1999 the answer is in #299.

**Comment by soso1999** [comment]
> @soso1999 the answer is in #299.

Thanks! I thought i am creasy! :)

**Comment by soso1999** [comment]
Ok, it worked for me! Thanks! 
One more question. I am trying to integrate ma Kostal Plenticore Inverter. How kann i set up EMS. I need some instructions. Editing config.json did nothing.
