### ISSUE TITLE
v1.2.4 Release Milestones

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#366]
v1.2.4 will be a bugfix and stability release. Currently v1.2.3 is the only version which will log in to the Tesla API given the captcha introduction. Unfortunately there's a number of issues introduced in v1.2.3 which affect core functionality and installation. v1.2.4 is a fix for these.

- Fix issue introduced which is causing charging to stop **done - merged**

- Fix for build issues in setuptools **done** - The requirement for setuptools_rust is a common issue with newer cryptography releases. I've specified cryptography prior to 3.4 to avoid this

- Fix #310 **done**

- Put temporary block in place to stop any core changes prior to release **pending**

**Comment by deece** [comment]
Can we fork off a stable branch for the release, and pull the existing PRs into main? I'm happy to help.
