### ISSUE TITLE
`policyValue()` should be able to access module properties

### ISSUE THREAD

**Issue by MikeBishop** [ngardiner/TWCManager#38]
In order to create policy requirements that make assertions about the state of the Powerwall (e.g. grid offline), the `policyValue()` function should be able to access the modules by name.  In the current architecture, they're not reachable from that function.  Fixing this might also be a good opportunity to fix #10 along the way, e.g. putting the modules into a dictionary and processing policy values against keys in the dictionary rather than hard-coding module names in the function.

**Comment by ngardiner** [comment]
Totally agree, @MikeBishop. I think this is the perfect opportunity to move toward the module instantiation and allow these lookups just as you've described. I'll take a look at this shortly and see if we can move it forward.
