### ISSUE TITLE
Tesla-API Could not parse JSON results 

### ISSUE THREAD

**Issue by surfarn** [ngardiner/TWCManager#389]
Hi, 

This is my first setup trying to get TWCManager up and running.  I do not have the RS485 device. I would like to use TWCManager as an loadbalancer. 

I keep getting this error:
![image](https://user-images.githubusercontent.com/53119062/142032567-3369f944-9b1a-4f2f-aee4-6af4dbca2895.png)

What could be wrong with my config?

**Comment by MikeBishop** [comment]
I just encountered this as well, and had to re-enter my tokens.  Perhaps updating a refresh token isn't working, @ngardiner?

**Comment by drexcia** [comment]
Having this issue as well after rebooting my pi and being prompted to re-enter in my username and password.

**Comment by MikeBishop** [comment]
I encountered something like this again -- it appears that my `settings.json` file was rolled back to pure default.  My tokens were gone, my non-scheduled charge rate, etc.

**Comment by drexcia** [comment]
Does using a token work as a workaround? I'm using Auth for Tesla to
generate a refresh token and then entering this into the settings page and
pressing save but my car isn't charging even though the charger is
currently offering up 32A.

I did try and use https://registration.teslatasks.com/generateTokens to get
a token but I'm not getting any response when I am entering in my
username/password and MFA token,

**Comment by rickhuizinga** [comment]
I encountered the same thing.  Had to re-enter my tokens on the settings page.

**Comment by ngardiner** [comment]
I'm aware of potential issues with refresh tokens, I'll close this issue off but it's primary focus to resolve.
