### ISSUE TITLE
Error connecting to MySQL database

### ISSUE THREAD

**Issue by lkyan** [ngardiner/TWCManager#393]
pi@raspberrypi:~ $ sudo docker-compose -f /home/pi/docker-compose.yml up
Starting pi_twcmanager_1 ... done
Attaching to pi_twcmanager_1
twcmanager_1  | 08:02:17 MySQLLoggi 20 Error connecting to MySQL database
twcmanager_1  | 08:02:17 MySQLLoggi 20 (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
twcmanager_1  | 08:02:18 🎮 HTTP     20 Serving at port: 8080
twcmanager_1  | 08:02:18 ⛽ Manager  20 TWC Manager starting as fake Master with id 7777 and sign 77

sudo mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 37
Server version: 10.3.31-MariaDB-0+deb10u1 Raspbian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| twcmanager         |
+--------------------+
4 rows in set (0.002 sec)

MariaDB [(none)]>

**Comment by tjikkun** [comment]
With ` mysql -u root -p` you connect via socket, while with 127.0.0.1 you connect via tcp. 
The equivalent command to test would be:
`mysql -h 127.0.0.1 -u root -p`
It doesn't look like TWCManager currently has support for connecting via socket, so maybe you can give access to mysql via tcp?
