### ISSUE TITLE
Feature Request: Restart via UI/HTTP control?

### ISSUE THREAD

**Issue by colwilliamsnz** [ngardiner/TWCManager#405]
Every few days my TWC “falls over” and refuses to charge the car without a restart of the Raspberry PI.

Would it be possible to add a method to the HTTP API and TWC UI to restart the underlying OS/Container/Device?

That way, instead of heading out to the garage to power off/on the PI, it’s a simple matter of opening a browser and clicking a button (or via the HTTP API, adding a suitable restart button to my Home Assistant TWC control panel) 😊

**Comment by ngardiner** [comment]
We wouldn't have permission to do so, unfortunately, as we run as an unprivileged user.

Might be better to add a cron job to reboot regularly?
