### ISSUE TITLE
Installation as per instructions failed - No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by MiRoCZ** [ngardiner/TWCManager#411]
Hello Nathan, 
strictly following latest Manual Instalation instructions (updated 6 days ago-thank you), but again get following error during executing command sudo make install:

![image](https://user-images.githubusercontent.com/79150049/153623990-cdc47889-ec82-4e58-8a52-a0d7c65138b8.png)

Latest Raspberry Pi Imager v1.7.1. used and Raspberry Pi OS Lite (32bit) - port of Debian Bullseye with no desktop (released 2022-01-28) environment installed on RPi Zero WH.

**Comment by colwilliamsnz** [comment]
Try this, worked for me: https://github.com/ngardiner/TWCManager/issues/356#issuecomment-897529340

Note the make install process takes a couple of hours…would be useful to add this detail to instructions :)

**Comment by MiRoCZ** [comment]
Thank you very much @colwilliamsnz for advice. I´ll try and report result. Definitelly agree that installation instructions / installation from the scratch, should be updated/tested periodically. It´s really frustrating for new potential contributors to spent days with unsuccessfull installations ...

**Comment by colwilliamsnz** [comment]
Try:

sudo apt-get install python3-pip

**Comment by MiRoCZ** [comment]
@colwilliamsnz 

![image](https://user-images.githubusercontent.com/79150049/153666650-7a384954-d07b-4825-bfc3-213e4f9e591a.png)


![image](https://user-images.githubusercontent.com/79150049/153666573-e22bc3b4-3dd6-4ae4-aeda-895e2ad1bad9.png)

**Comment by MiRoCZ** [comment]
![image](https://user-images.githubusercontent.com/79150049/153669346-d9c0c38a-4937-4333-b522-4744657558a8.png)
now in progress with warnings. I will see the result will be after 2 hours as you mentioned :-) . THX

**Comment by MiRoCZ** [comment]
YEEESSSS, it´s finally started communicate. THANK YOU VERY MUCH @colwilliamsnz  !!!

![image](https://user-images.githubusercontent.com/79150049/153671454-3766df0e-824a-4d64-a69f-89d2a44e6aeb.png)

1 step forward, great :-),  and now how to make HTTP control functional.

**Comment by Flitzer42** [comment]
Here a short instruction how to install from scratch on Rapi 3B:
1.	Install OS on SD card: Raspberry PI OS LITE (LEGACY)
2.	Activate SSH: copy empty file named “ssh” to “boot”
3.	Insert SDcard in Raspi
4.	Power up
5.	Connect with putty “pi”, “raspberry”
6.	Update OS: 
    sudo apt-get update
7.	Install phyton
    sudo apt-get install -y git python3 python3-setuptools python3-dev libatlas-base-dev
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
8.	Install TWC Manager
    git clone https://github.com/ngardiner/TWCManager
    cd TWCManager
    git checkout main
    make install
  This takes a while, be patient!
9.	Setup TWC Manager as service to be started automatically
sudo cp contrib/twcmanager.service /etc/systemd/system/twcmanager.service
sudo systemctl enable twcmanager.service
10.	Restart System
sudo reboot
11.	Control operation
journalctl -f

Hints: TCM Manager needs a RS485 USB device plugged in to work.

I think, HTTP control should work out of the box

The legacy interface need to be enabled in the config file:
Add:
  "IPC": {
    "enabled": true
  },
in the section "control".
To permanently disable "track green energy",  add:
          "Track Green Energy":{
            "match": [ "" ],
            "condition": [ "false" ],
            "value": [ "" ]
          },
to section "restrictions". This disables the charge power control in TWC manager and allows full control from outside (HTTP).

**Comment by ngardiner** [comment]
Would be good to hear if these issues are resolved for you in v1.2.4

**Comment by MiRoCZ** [comment]
Hi Nathan @ngardiner,

installation from the scratch (Latest Raspberry Pi Imager v1.7.1. used and Raspberry Pi OS Lite (32bit) - port of Debian Bullseye with no desktop (released 2022-01-28), as per current instructions at https://github.com/ngardiner/TWCManager/blob/main/docs/Software_Manual.md , resulted again in error: 

![image](https://user-images.githubusercontent.com/79150049/154810526-30ec4051-f421-4b69-896c-dfd22b7adeb0.png)

BUT TWC Manager finally started without errors and with web interface when I tried to upgrade as per instructions by command:

sudo pip install --upgrade twcmanager

which was not possible to execute, so I had to install 

sudo apt-get install python3-pip

and then 

sudo pip install --upgrade twcmanager

was executed and TWC Manager successfully started by command

sudo -u twcmanager python -m TWCManager

I´m not familiar how to edit documentation, but it would be helpfull for others to add comment to upgrade procedure (sudo apt-get install python3-pip). 

Thank you for this great project !

**Comment by ngardiner** [comment]
Thanks, I've updated the documentation and a new release will be available shortly.
