### ISSUE TITLE
Limiting charging current - each change go to 16A at first 

### ISSUE THREAD

**Issue by MiRoCZ** [ngardiner/TWCManager#414]
Do you also experience following behaviour when each current limit change initiated by TWC Manager is responded by Slave TWC by setting 16A (max. limit) at first for 5-6 second as visible on screenshot when current increased gradually up to 12,38A and then finally adjusted to requested 7A. This currents are confirmed by realtime meter measurements.
Is it possible to make TWC current change without setting 16A at first each time?

![image](https://user-images.githubusercontent.com/79150049/154991182-88cec9d9-3fe1-4da1-aedc-8837099a87bf.png)

**Comment by ngardiner** [comment]
Yes, you can disable spiking amps in the Debug tab of the Web UI, however we do it for a reason - vehicles can get stuck when changing the rate and the mechanism is there to avoid that situation. If you turn it off, just be aware that the vehicle not responding to variations in the charge rate is not a bug, it is why we do it.

![image](https://user-images.githubusercontent.com/25845228/155069731-da50debf-8ac9-4d0d-8c5f-902e61c5de73.png)
