### ISSUE TITLE
Tesla token is not refreshing

### ISSUE THREAD

**Issue by Dustovsky** [ngardiner/TWCManager#419]
Hi guys

I just upgraded to 1.2.4 and have now the issue, that the TWCManager is apparently not updating the access token for the Tesla API.
What I did / what it does or doesn't:
- put access and refresher token in the respective fields in the setting menu
- The stop command is being executed correctly, but only for the first 8h
- then, it looks as if the token is not recognized/refreshed, as the stop command is not executed by the car
- the charge power goes back to 6A and remains there forever

Anybody an idea what's wrong?

**Comment by ngardiner** [comment]
Please see #299 - closing duplicate
