### ISSUE TITLE
Issue with charging schedule/settings

### ISSUE THREAD

**Issue by danielsan1** [ngardiner/TWCManager#448]
Hey all - sorry for all the issues in the last couple of weeks... I hope everything will be back to normal soon :-)

This time (after updating "startStopDelay" and "greenEnergyFlexAmps" - but I can't see a connection to this) I have an issue with the charging schedule and non-schedule settings. 
I still don't fully understand how the schedule is working but as far as I get it I set the following (I'll attach some screenshots):
Between 9am and 5pm TWCManager will charge with solar surplus. (schedule) Between 5pm and 9am next day it will not charge (non-schedule settings)
But the actual behavior is: At any time "don't charge" (issue #1) and the car is charging anyway with 6A (issue #2) This is very strange to me and I have no idea why that happens. And it never happened before...
Unfortunately I also do not understand the "Policy" screen.

Thanks again for your help!
Daniel

**"don't charge" but in schedule time "solar surplus"**
![dont charge but in schedule](https://user-images.githubusercontent.com/3944456/164433004-e1b3046a-8d3a-4813-b2a8-c5e1bc72c320.PNG)

**it's charging without A offer**
![charging without offer](https://user-images.githubusercontent.com/3944456/164433008-2e962299-03d1-4c23-8e1b-c8e0b3d15cde.PNG)

![settings](https://user-images.githubusercontent.com/3944456/164432989-3e61e7c1-5fa7-4de5-b381-3830c70154dc.png)

![policy](https://user-images.githubusercontent.com/3944456/164432995-eac752b5-f111-4cb0-9d26-a05310350405.png)

![schedule](https://user-images.githubusercontent.com/3944456/164433000-6d67e0b4-b900-49bd-a671-50bb1d4e346a.png)

**Comment by MikeBishop** [comment]
A few things interleaved there:
- Up until [two days ago](https://github.com/ngardiner/TWCManager/pull/443), the highlighted behavior on the home screen was your selected Non-Scheduled Charging action -- which defaults to "Don't charge."  The newly merged PR will make it reflect the current policy's behavior instead, which I think everyone agrees is more intuitive.
- Based on your settings and the policy option, you should currently be in Track Green Energy, which will offer your solar excess to the car.  Except you don't currently have any excess, so the offer is zero.  At the TWC level, that means we'll let the TWC offer the minimum (6A), but tell cars to stop charging.
- If the car begins charging, it will be allowed to continue for `startStopDelay` seconds before being told to stop, to see if the car's presence changes the selected policy or if enough power becomes available to let it continue.
- Is TWCManager successfully sending commands to the car via the Tesla API?  (Look for log output to see the attempts and success/failure.)  If not, the car doesn't know to stop charging and will continue at the minimum until the TWC offers more.

**Comment by danielsan1** [comment]
Thanks Mike for the very good explanation and clarification! I think now I got it and had indeed some misunderstandings on how TCWManager works :)

1) I also agree that it is more intuitive to show current policy's behavior. How can I get the update? With an upgrade to 1.3 ? Should I go for it now? :) Nevertheless, it’s working as it should at the moment. (Don’t charge non-scheduled)
2) I really had a problem with the Tesla API but now it should be fixed. That issue mixed with my misunderstanding of how TWCM works caused my confusion. I understand now: 
- When I plug in the car it will start charging in any case. Than it will check the current policy and will stop or keep charging accordingly. Right?
- It than will check all 5 min (my newly set delay) if it’s still allowed to charge according to the current policy. 
Is that correct?

If yes, everything should be fine now. I fixed the API, plugged in the car, it started charging (although there was not enough green energy) and it stopped after a few minutes (maybe 5 but I’m not sure).

In the context of the API may I ask an unrelated question: What are the pros/cons of the different “Charge Rate Control” options (TWCM/TeslaAPI)? Which variant is preferable?

Again, thanks for all the support!

**Comment by ngardiner** [comment]
Hi @danielsan1,

There's a new easy way to upgrade TWCManager which should help you with the upgrade, but it will only appear after we release the next version as it works by querying pypi for the latest version of the package. If you can give us a little bit of time, I can get a new version out shortly thanks to all the new fixes and features that @dtiefnig and @MikeBishop have contributed.

The upgrade process can be performed from a browser. I'll need your help to test it, I just need to make some improvements to that code which I could get done at the end of this week and we'll go ahead and release a new version, and you'll have the new and more accurate charge state feature available.

I'll start a discussion shortly for those who want to test the new upgrade feature, and who would like to give their feedback.

**Comment by danielsan1** [comment]
Thanks all of you guys for the great work!
I’ll definitely help testing wherever I can.

**Comment by danielsan1** [comment]
Hi @MikeBishop @ngardiner 
I just want to check in on my additional question about the pros/cons of the different “Charge Rate Control” options (TWCM/TeslaAPI) and which variant is preferable? :)
Thanks guys!

**Comment by MikeBishop** [comment]
Sure -- controlling the TWC directly is the older (and definitely better tested) method.  Using the Tesla API is newer and requires a relatively current firmware version on the car.  There's no direct advantage to it (other than that it can command a 5A charge rate, versus the 6A minimum of the other method), but it's very exciting for a different reason:  It has the potential to enable a future direction that doesn't requiring wiring anything into the inside of the TWC, nor perhaps even require a TWC at all.

**Comment by danielsan1** [comment]
Thanks for the explanation. That sounds really exiting for a “TWCManager” for everyone 😊
