### ISSUE TITLE
Current Policy in MQTT-status

### ISSUE THREAD

**Issue by bikeymouse** [ngardiner/TWCManager#467]
The [MQTT-status interface](https://github.com/ngardiner/TWCManager/blob/main/docs/modules/Status_MQTT.md) is missing the Current Policy. So this is now the only parameter I have to poll using the REST-API interface.

Could this be added? I would propose to publish this on: "prefix/all/currentPolicy"

**Comment by ngardiner** [comment]
Absolutely, this should be fairly straightforward, I'll take a look at it now.

**Comment by ngardiner** [comment]
Done, I've added this in 60887f7 and tested it appears on MQTT broker and HASS

**Comment by bikeymouse** [comment]
Wow, that is quick thank you!
