### ISSUE TITLE
Check and Remove Globals in TWCManager

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#5]
There are still globals in TWCManager to be checked & removed:

data = ''
dataLen = 0
ignoredData = bytearray()
msg = bytearray()
msgLen = 0
lastTWCResponseMsg = None

numInitMsgsToSend = 10
msgRxCount = 0

idxSlaveToSendNextHeartbeat = 0
timeLastkWhDelivered = time.time()
timeLastkWhSaved = time.time()
timeLastHeartbeatDebugOutput = 0

webMsgPacked = ''
webMsgMaxSize = 300
webMsgResult = 0

timeTo0Aafter06 = 0
timeToRaise2A = 0

**Comment by AndySchroder** [comment]
Please note, https://github.com/AndySchroder/TWCManager/commit/1951b8bd9d83732abce456e0205c7f7bcb83b988 moves these into a class and should resolve this issue if you will merge it into your branch.
