### ISSUE TITLE
images on dockerhub are out of date

### ISSUE THREAD

**Issue by dtiefnig** [ngardiner/TWCManager#541]
Hi!

Could you probably push 1.3.1 to dockerhub?

"latest" tag of twcmanager/twcmanager there still points to a 6 months old dev version.

Thanks,
Daniel

**Comment by bikeymouse** [comment]
I Second that. 
Latest is indeed 6 months old: https://hub.docker.com/r/twcmanager/twcmanager/tags

**Comment by bikeymouse** [comment]
P.s. this is a workaround: https://github.com/ngardiner/TWCManager/issues/533#issuecomment-1837570599

**Comment by ngardiner** [comment]
Apologies, let me fix this now (and thank you for the heads-up)

**Comment by ngardiner** [comment]
This has been fixed
