### ISSUE TITLE
car_api_charge() and enforcePolicy() prevent car from sleeping

### ISSUE THREAD

**Issue by dtiefnig** [ngardiner/TWCManager#573]
Not sure if I'm missing something, but since upgrade to 1.3.2 my car does not sleep anymore when it is at home. Maybe limited to certain conditions, did not have much opportunity to test.

`car_api_charge()` in `Vehicle/TeslaAPI.py` is setting `vehicle.stopAskingToStartCharging` to `true` if the car is unplugged, fully charged or currently charging already. On subsequent calls (which happen once every second) the function first checks if the last call to the function was more than 60 seconds ago, and if so it then checks if a car has `vehicle.stopAskingToStartCharging` set. It then avoids asking the car to start charging again, so the car can sleep.

The problem I currently see is that `setChargingPerPolicy()` in `Policy/Policy.py`  is calling `self.enforcePolicy()` if all policy conditions are met, and this in turn is enforcing `vehicle.stopAskingToStartCharging` to `false` for all cars. This happens twice per minute. A comment there says `Clear stopAskingToStartCharging so we try charging each car at least once` and I believe this is working too well.

`git blame` tells me the code got there 2023-11-18 by @RichieB2B, the message on commit 51d948c says it is meant to `Clear stopAskingToStartCharging when switching policies` but it seems this happens every time the policy is determined, even if it is not changed.

I'd be quite surprised if others wouldn't be affected by this. It is not super easy to notice the car is not sleeping though. Is anyone seeing the same behavior? In the log, it looks like the following. Log lines marked `+++` have been patched into the code by me, the `+++ car_api_charge called` lines are repeated every second.

> [...]
> Apr  1 15:24:41 charon twcman[925]: 🚗 TeslaAPI 20 +++ car_api_charge called, charge is True, Orion has vehicle.stopAskingToStartCharging False
> Apr  1 15:24:47 charon twcman[925]: 🚗 TeslaAPI 17 Orion: start charge response{'response': {'reason': 'complete', 'result': False}}
> Apr  1 15:24:47 charon twcman[925]: 🚗 TeslaAPI 20 Orion is done charging or already trying to charge or not connected to a charger.  Stop asking to start charging.
> Apr  1 15:24:47 charon twcman[925]: 🚗 TeslaAPI 20 +++ car_api_charge called, charge is True, Orion has vehicle.stopAskingToStartCharging True
> [...]
> Apr  1 15:25:03 charon twcman[925]: 🚗 TeslaAPI 20 +++ car_api_charge called, charge is True, Orion has vehicle.stopAskingToStartCharging True
> Apr  1 15:25:04 charon twcman[925]: ⛽ Policy   14 All policy conditions have matched. Policy chosen is Non Scheduled Charging
> Apr  1 15:25:04 charon twcman[925]: ⛽ Policy   20 +++ Orion has vehicle.stopAskingToStartCharging True, setting to False
> Apr  1 15:25:04 charon twcman[925]: ⛽ Manager  20 Limiting charging to 12.00A.
> Apr  1 15:25:04 charon twcman[925]: ⛽ Manager  20 Charge when above 6A (minAmpsPerTWC).
> Apr  1 15:25:04 charon twcman[925]: 🚗 TeslaAPI 20 +++ car_api_charge called, charge is True, Orion has vehicle.stopAskingToStartCharging False
> [...]

**Comment by RichieB2B** [comment]
Good catch. I definitely meant to only do this on policy change but indeed included it in code that runs every minute.
