### ISSUE TITLE
Implement password authentication for Powerwall2 EMS module

### ISSUE THREAD

**Issue by ngardiner** [ngardiner/TWCManager#9]
Currently, the Powerwall2 EMS module does not support password authentication for Powerwall2.

**Comment by ngardiner** [comment]
Added password authentication in 686954f. Not yet tested, if errors occur with password authentication, try omitting password in the configuration file, as online API references suggest Powerwall API doesn't need authentication to fetch metering data.

**Comment by MikeBishop** [comment]
I believe this is fixed by #44; sorry I forgot to tag it in the PR.
