### ISSUE TITLE
comma missing in config.json

### ISSUE THREAD

**Issue by AndySchroder** [ngardiner/TWCManager#95]
Need a comma on the end of this line:

https://github.com/ngardiner/TWCManager/blob/v1.2.0/etc/twcmanager/config.json#L201

**Comment by AndySchroder** [comment]
Actually, I think you need to add a }, which would make line 201

}},

**Comment by AndySchroder** [comment]
Also, line 161 has a comma on it that should be removed.

**Comment by ngardiner** [comment]
Good pickup, this is fixed now, thanks @AndySchroder
